### ISSUE TITLE
Define policy for deployment approval

### ISSUE THREAD

**Issue by david3107** [dcodx/gitarmor#6]
## Current situation

Github offer simple [deployment protection rules](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments). If a deployment matches an environment, designated users will need to approve. 

## Improvement 

Use Gitarmor to 
1. check that the approvers are correctly defined in the repo
2. define more complex rule to automatically approve deployments (maybe this requires a separate issue)

## Example 1

```yml
deployment:
    prod: 
       - user1
       - user2
```
## Example 2
```yml
deployment:
  auto-approve:
    dev:
      folders:
        - "/*"
  approval-required:
    prod:
      folders:
        - "a/authN":
            - user1
            - user2
        - authZ:
            - user1
            - user2

```
